name: Build & Publish Electron App

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Enable corepack & install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.15.0 --activate
          pnpm --version

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build & Publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: pnpm run publish:always
